# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.66.2"
#import "../../../react-viro/Examples/ios/fastlane/Fastfile"

default_platform :ios
platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # carthage
  end

  desc "Build test bed app"
  lane :release do
#    Dir.chdir("../../../react-viro/Examples/ios/ViroExample") do
#      release_react_viro_lib
#    end 
    # Clean ViroMediaApp
    sh("xcodebuild clean -workspace ViroMediaApp.xcworkspace/ -scheme ViroMediaApp -configuration Release | xcpretty -c")

    # Build ViroMediaApp
    sh("xcodebuild -workspace ViroMediaApp.xcworkspace/ -scheme ViroMediaApp -configuration Release | xcpretty -c")
  end
  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
