# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.66.2"

default_platform :android
# Import ViroRenderer's fastfile

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end
  lane :clean do
    gradle(task:"clean")
  end

  desc "Build dependencies and then build test bed app"
  lane :clean_npm_install do
    Dir.chdir("../../") do
      sh("rm -rf node_modules")
      sh("npm install ../react-viro/react-viro-*.tgz")
      sh("npm install") 
    end
    gradle(task:"assembleGvrRelease")
  end

  lane :apply_patch do
    sh("bash applyPatch.sh")
  end

  lane :gvr_release do
    gradle(task:"assembleGvrRelease")
  end
  
  lane :upload_s3 do
    sh("cp app/build/outputs/apk/gvr/release/app-gvr-release.apk ~/tmp/s3_artifacts/viro-media-app-gvr-release.apk")
    
  end
  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
